name: doudou
description: "A Jellyfin music player app"
publish_to: 'none'
version: 5.0.0

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP requests
  dio: ^5.4.0
  http: ^1.1.0
  
  # Audio playbook
  just_audio: ^0.10.4
  audio_service: ^0.18.12
  
  # State management
  provider: ^6.1.5
  
  # UI components
  cached_network_image: ^3.4.1
  
  # Storage and Caching
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_cache_manager: ^3.4.1
  
  # App info
  package_info_plus: ^8.0.2
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
