icon: assets/icons/icon.png
summary: An application to stream Music
group: Application/Multimedia
vendor: openlyst
packager: openlyst
license: GPLv3
url: https://gitlab.com/Openlyst/doudou

requires:
  - mpv-libs
  - libappindicator

display_name: Doudou

keywords:
  - Opensource
  - Music
  - Streaming
  - Flutter

generic_name: Music Application

categories:
  - Music

startup_notify: true