display_name: Doudou

icon: assets/icons/icon.png

keywords:
  - Music
  - Audio
  - Streaming
  - Jellyfin
  - Media
  - Player

generic_name: Music Streaming Client

categories:
  - Audio
  - Music
  - Player
  - AudioVideo

startup_notify: true

# Automatically detect shared libraries
include: []
