#!/usr/bin/env bash
set -euo pipefail

patch_terminate_restart_swift() {
  local file="$1"
  [ -f "$file" ] || return 0

  # Flutter/Xcode 2026 toolchains can fail when the plugin contains:
  # if let flutterEngine = registrar.messenger() as! FlutterEngine {
  # Convert it to a stable form that preserves block structure.
  perl -0777 -i -pe 's/^([ \t]*)if\s+let\s+flutterEngine\s*=\s*registrar\.messenger\(\)\s*as!\s*FlutterEngine\s*\{/$1if true {\n$1    let flutterEngine = registrar.messenger() as! FlutterEngine/gm' "$file"
}

# Local vendored plugin (preferred)
patch_terminate_restart_swift "packages/terminate_restart/ios/Classes/TerminateRestartPlugin.swift"

# iOS symlinked plugin path generated by Flutter
patch_terminate_restart_swift "ios/.symlinks/plugins/terminate_restart/ios/Classes/TerminateRestartPlugin.swift"

# Fallback: git/path plugin copies in pub cache
if [ -d "$HOME/.pub-cache" ]; then
  while IFS= read -r plugin_file; do
    patch_terminate_restart_swift "$plugin_file"
  done < <(find "$HOME/.pub-cache" -type f -path "*/terminate_restart*/ios/Classes/TerminateRestartPlugin.swift" 2>/dev/null || true)
fi

echo "iOS prebuild patch complete"
